# Generated by Django 2.2.4 on 2019-10-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=500, verbose_name='Detalhes')),
                ('number_events', models.IntegerField(verbose_name='Quantidade de Eventos')),
                ('occurrence_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Ocorrência')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
