# Generated by Django 2.2.4 on 2019-10-21 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Password')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='Ultimo Login')),
            ],
        ),
    ]
