# Generated by Django 2.2.5 on 2019-10-26 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_environment'),
        ('api', '0003_level'),
    ]

    operations = [
    ]
